server:
  port: 8081

spring:
  application:
    name: hybris-data-update
  data:
    mongodb:
      database: DIT1-TEST
      host: 10.62.109.136
      port: 27017
  kafka:
    bootstrap-servers: 10.62.100.218:9092
    consumer:
      group-id: hybris-data-consumer-group
      #enable-auto-commit: true
      #auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

